[package]
name = "yocto_client"
description = "Rust client for yocto"
version = "0.0.2"
authors = ["Alexander Becker"]
license = "MIT"
repository = "https://github.com/alebeck/yocto-rust"
edition = "2018"

[dev-dependencies]
yocto = "0.2.0"
log = "0.3.0"